"""add ph no

Revision ID: b4a1d118577a
Revises: bf91115ec050
Create Date: 2023-08-12 17:26:40.727416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4a1d118577a'
down_revision: Union[str, None] = 'bf91115ec050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ph_no', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ph_no')
    # ### end Alembic commands ###
